# Generated by Django 6.0.3 on 2026-04-04 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transport', models.CharField(choices=[('transporteur_externe', 'Transporteur externe'), ('camion_eip', 'Camion EIP')], max_length=30)),
                ('transporteur', models.CharField(blank=True, max_length=100)),
                ('numero_suivi', models.CharField(blank=True, max_length=100)),
                ('cout_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('prepare', 'Préparé'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('partiel', 'Livraison partielle')], default='prepare', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='clients.adresselivraison')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_chauffeur', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_crees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_prevue', models.PositiveIntegerField()),
                ('quantite_livree', models.PositiveIntegerField(default=0)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='livraisons.bonlivraison')),
            ],
            options={
                'verbose_name': 'Ligne de livraison',
                'verbose_name_plural': 'Lignes de livraison',
            },
        ),
    ]
