# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('transporteur', models.CharField(blank=True, max_length=100)),
                ('no_suivi', models.CharField(blank=True, max_length=100)),
                ('mt_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('prepare', 'Préparé'), ('expedie', 'Expédié'), ('livre', 'Livré'), ('partiel', 'Partiel')], default='prepare', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='clients.adresselivraison')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_crees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='dossiers.dossier')),
                ('type_transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='parametres.typetransport')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte_prevue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qte_livree', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('qte_restante', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='livraisons.bonlivraison')),
            ],
            options={
                'verbose_name': 'Ligne livraison',
                'verbose_name_plural': 'Lignes livraison',
            },
        ),
    ]
