# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mt_regle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='dossiers.dossier')),
                ('mode_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='parametres.modepaiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emis', 'Émis'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneAvoir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tgc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.avoir')),
            ],
            options={
                'verbose_name': 'Ligne avoir',
                'verbose_name_plural': 'Lignes avoir',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tgc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pru', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_factures', to='articles.article')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Ligne facture',
                'verbose_name_plural': 'Lignes facture',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements_crees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='facturation.facture')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='parametres.modepaiement')),
            ],
            options={
                'verbose_name': 'Règlement',
                'verbose_name_plural': 'Règlements',
                'ordering': ['-date'],
            },
        ),
    ]
