# Generated by Django 6.0.4 on 2026-04-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_categorie_remove_article_sections_and_more'),
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_factures', to='articles.articlestock'),
        ),
    ]
