# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBonCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qte_recue', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ligne bon de commande',
                'verbose_name_plural': 'Lignes bon de commande',
            },
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('envoye', 'Envoyé'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date', models.DateField()),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon de commande',
                'verbose_name_plural': 'Bons de commande',
                'ordering': ['-date'],
            },
        ),
    ]
