# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_commande', to='articles.fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='articles.article'),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='bon_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.boncommande'),
        ),
    ]
