# Generated by Django 6.0.4 on 2026-04-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_initial'),
        ('articles', '0010_remove_article_categorie_remove_article_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneboncommande',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='articles.articlestock'),
        ),
    ]
