# Generated by Django 6.0.3 on 2026-04-04 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur', models.TextField()),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('decimal', 'Décimal'), ('entier', 'Entier'), ('booleen', 'Booléen'), ('email', 'Email'), ('url', 'URL')], default='texte', max_length=20)),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('fiscal', 'Fiscal'), ('machine', 'Machine'), ('operateur', 'Opérateur'), ('email', 'Email'), ('impression', 'Impression')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['categorie', 'libelle'],
            },
        ),
    ]
