# Generated by Django 6.0.3 on 2026-04-04 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catégorie article',
                'verbose_name_plural': 'Catégories articles',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mode de paiement',
                'verbose_name_plural': 'Modes de paiement',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('valeur', models.TextField()),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('decimal', 'Décimal'), ('entier', 'Entier'), ('booleen', 'Booléen'), ('email', 'Email'), ('url', 'URL')], default='texte', max_length=20)),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('fiscal', 'Fiscal'), ('machine', 'Machine'), ('operateur', 'Opérateur'), ('email', 'Email'), ('impression', 'Impression')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TGC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TGC',
                'verbose_name_plural': 'TGC',
                'ordering': ['taux'],
            },
        ),
        migrations.CreateModel(
            name='TypeLigneDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type ligne dossier',
                'verbose_name_plural': 'Types ligne dossier',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de machine',
                'verbose_name_plural': 'Types de machine',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeTransport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de transport',
                'verbose_name_plural': 'Types de transport',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('abreviation', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
                'ordering': ['libelle'],
            },
        ),
    ]
