# Generated by Django 6.0.3 on 2026-04-06 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerotationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_doc', models.CharField(choices=[('devis', 'Devis'), ('dossier', 'Dossier'), ('facture', 'Facture'), ('avoir', 'Avoir'), ('livraison', 'Bon de livraison'), ('commande', 'Bon de commande')], max_length=20, unique=True)),
                ('prefixe', models.CharField(blank=True, default='', max_length=10)),
                ('millesime', models.CharField(blank=True, default='', max_length=4)),
                ('separateur', models.CharField(blank=True, default='-', max_length=2)),
                ('longueur', models.PositiveIntegerField(default=5)),
                ('numero_courant', models.PositiveIntegerField(default=1)),
                ('reset_annuel', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Numérotation document',
                'verbose_name_plural': 'Numérotations documents',
                'ordering': ['type_doc'],
            },
        ),
    ]
