# Generated by Django 6.0.4 on 2026-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0003_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordre', 'libelle'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
