# Generated by Django 6.0.3 on 2026-04-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_article_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='seuil_minimum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_actuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock_apres',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock_avant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
