# Generated by Django 6.0.3 on 2026-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_seuil_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pru_moyen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='article',
            name='valeur_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='valeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
