# Generated by Django 6.0.3 on 2026-04-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_pru_moyen_article_valeur_stock_and_more'),
        ('parametres', '0002_numerotationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tgc_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_achat', to='parametres.tgc', verbose_name='TGC achat'),
        ),
        migrations.AddField(
            model_name='article',
            name='tgc_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_vente', to='parametres.tgc', verbose_name='TGC vente'),
        ),
    ]
