# Generated by Django 6.0.3 on 2026-04-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tgc_achat_article_tgc_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_vente_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix de vente HT'),
        ),
    ]
