# Generated by Django 6.0.4 on 2026-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_alter_ligneboncommande_article'),
        ('articles', '0010_remove_article_categorie_remove_article_sections_and_more'),
        ('dossiers', '0006_lignedevis_article_service_and_more'),
        ('facturation', '0002_alter_lignefacture_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
