# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxHoraire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('machine', 'Machine'), ('operateur', 'Opérateur')], max_length=20)),
                ('libelle', models.CharField(max_length=100)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Taux horaire',
                'verbose_name_plural': 'Taux horaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='parametres.typemachine')),
                ('taux_horaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='planning.tauxhoraire')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['type__libelle', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanningCreneau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='dossiers.dossier')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='planning.machine')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Créneau planning',
                'verbose_name_plural': 'Créneaux planning',
                'ordering': ['debut'],
            },
        ),
    ]
