# Generated by Django 6.0.3 on 2026-04-04 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoutMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duree_estimee_h', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duree_reelle_h', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Coût machine',
                'verbose_name_plural': 'Coûts machines',
            },
        ),
        migrations.CreateModel(
            name='CoutOperateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duree_estimee_h', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duree_reelle_h', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Coût opérateur',
                'verbose_name_plural': 'Coûts opérateurs',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('devis_envoye', 'Devis envoyé'), ('accepte', 'Accepté'), ('en_fabrication', 'En fabrication'), ('annule', 'Annulé'), ('expedie', 'Expédié'), ('facture', 'Facturé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('priorite', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=20)),
                ('visibilite_client', models.BooleanField(default=False)),
                ('notes_internes', models.TextField(blank=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichierDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bat', 'BAT'), ('visuel', 'Visuel'), ('bon_a_tirer', 'Bon à tirer'), ('autre', 'Autre')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='dossiers/fichiers/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fichier dossier',
                'verbose_name_plural': 'Fichiers dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('matiere', 'Matière'), ('consommable', 'Consommable'), ('sous_traitance', 'Sous-traitance')], default='matiere', max_length=20)),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ligne article',
                'verbose_name_plural': 'Lignes articles',
            },
        ),
        migrations.CreateModel(
            name='SpecsTechniques',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_final', models.CharField(blank=True, max_length=50)),
                ('format_ouvert', models.CharField(blank=True, max_length=50)),
                ('nb_pages', models.PositiveIntegerField(default=1)),
                ('type_impression', models.CharField(blank=True, choices=[('offset', 'Offset'), ('numerique', 'Numérique'), ('serigraphie', 'Sérigraphie'), ('autre', 'Autre')], max_length=20)),
                ('recto_verso', models.CharField(choices=[('recto', 'Recto'), ('recto_verso', 'Recto/Verso')], default='recto', max_length=20)),
                ('pelliculage', models.CharField(choices=[('aucun', 'Aucun'), ('brillant', 'Brillant'), ('mat', 'Mat'), ('soft_touch', 'Soft Touch')], default='aucun', max_length=20)),
                ('facon', models.CharField(blank=True, max_length=255)),
                ('support', models.CharField(blank=True, max_length=255)),
                ('grammage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Specs techniques',
                'verbose_name_plural': 'Specs techniques',
            },
        ),
        migrations.CreateModel(
            name='Tirage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_selectionne', models.BooleanField(default=False)),
                ('marge_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('marge_reelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imposition_json', models.JSONField(blank=True, null=True)),
                ('imposition_svg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tirage',
                'verbose_name_plural': 'Tirages',
                'ordering': ['quantite'],
            },
        ),
    ]
