# Generated by Django 6.0.3 on 2026-04-04 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('clients', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_fabrication', 'En fabrication'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('livre', 'Livré')], default='en_fabrication', max_length=20)),
                ('priorite', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('tres_urgent', 'Très urgent')], default='normal', max_length=20)),
                ('visible_client', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('notes_fab', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier', to='dossiers.devis')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tgc', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='articles.article')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dossiers.devis')),
            ],
            options={
                'verbose_name': 'Ligne devis',
                'verbose_name_plural': 'Lignes devis',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('qte_prevue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qte_consommee', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pru', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dossiers', to='articles.article')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dossiers.dossier')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dossier', to='parametres.typelignedossier')),
            ],
            options={
                'verbose_name': 'Ligne dossier',
                'verbose_name_plural': 'Lignes dossier',
            },
        ),
    ]
