# Generated by Django 6.0.3 on 2026-04-04 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_initial'),
        ('clients', '0001_initial'),
        ('dossiers', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coutmachine',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couts', to='planning.machine'),
        ),
        migrations.AddField(
            model_name='coutmachine',
            name='taux_horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couts_machines', to='planning.tauxhoraire'),
        ),
        migrations.AddField(
            model_name='coutoperateur',
            name='operateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couts_operateurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coutoperateur',
            name='taux_horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couts_operateurs', to='planning.tauxhoraire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='clients.client'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dossier_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retirages', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='technico_commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_tc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichierdossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='fichierdossier',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichiers_uploades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dossiers', to='articles.article'),
        ),
        migrations.AddField(
            model_name='specstechniques',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='tirage',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirages', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='lignearticle',
            name='tirage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_articles', to='dossiers.tirage'),
        ),
        migrations.AddField(
            model_name='coutoperateur',
            name='tirage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts_operateurs', to='dossiers.tirage'),
        ),
        migrations.AddField(
            model_name='coutmachine',
            name='tirage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts_machines', to='dossiers.tirage'),
        ),
    ]
