# Generated by Django 6.0.3 on 2026-04-05 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        ('parametres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='qte',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignedossier',
            name='qte_consommee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lignedossier',
            name='qte_prevue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PointageAtelier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qte_prevue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qte_reelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='dossiers.dossier')),
                ('ligne_dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='dossiers.lignedossier')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to=settings.AUTH_USER_MODEL)),
                ('type_tache', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='parametres.typelignedossier')),
            ],
            options={
                'verbose_name': 'Pointage atelier',
                'verbose_name_plural': 'Pointages atelier',
                'ordering': ['-created_at'],
            },
        ),
    ]
