# Generated by Django 6.0.3 on 2026-04-06 05:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_alter_lignedevis_qte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Devis', 'verbose_name_plural': 'Devis'},
        ),
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.RenameField(
            model_name='devis',
            old_name='remise',
            new_name='remise_globale',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='lignedevis',
            name='devis',
        ),
        migrations.AddField(
            model_name='devis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devis',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='pru',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='type',
            field=models.CharField(choices=[('article', 'Article catalogue'), ('libre', 'Ligne libre'), ('sous_total', 'Sous-total'), ('texte', 'Texte')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VarianteDevis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gain', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='dossiers.devis')),
            ],
            options={
                'verbose_name': 'Variante devis',
                'verbose_name_plural': 'Variantes devis',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='variante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossier', to='dossiers.variantedevis'),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='dossiers.variantedevis'),
        ),
    ]
