# Generated by Django 6.0.4 on 2026-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_lignedevis_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='format',
            field=models.CharField(blank=True, max_length=100, verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='devis',
            name='papier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Papier'),
        ),
        migrations.AddField(
            model_name='devis',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AddField(
            model_name='variantedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='designation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
