# Generated by Django 6.0.4 on 2026-04-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_article_categorie_remove_article_sections_and_more'),
        ('dossiers', '0005_devis_urgent_format_papier_variantedevis_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='article_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='articles.articleservice'),
        ),
        migrations.AddField(
            model_name='lignedossier',
            name='article_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dossiers', to='articles.articleservice'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='articles.articlestock'),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='type',
            field=models.CharField(choices=[('article', 'Article stock'), ('service', 'Service'), ('libre', 'Ligne libre'), ('texte', 'Texte')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedossier',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_dossiers', to='articles.articlestock'),
        ),
    ]
