# Generated by Django 6.0.3 on 2026-04-04 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stock_bas', 'Stock bas'), ('stock_insuffisant', 'Stock insuffisant'), ('derive_rentabilite', 'Dérive rentabilité'), ('validation_requise', 'Validation requise'), ('statut_dossier', 'Changement statut dossier'), ('autre', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('objet_id', models.UUIDField(blank=True, null=True)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
